package:
  name: titrato
  version: "0.0.3"

source:
  path: ../..

build:
  number: 0

requirements:
  build:
    - python=3.7
    - setuptools    

  run:
    - python
    - scipy
    - numpy
    - matplotlib
    - pandas
    - networkx
    - pydot
    - adjusttext
    - typing_extensions
    - networkx
    - tqdm
    - uncertainties
    - seaborn

test:
  requires:
    - pytest
  imports:
    - titrato

about:
  home: add_url_here
  license: MIT License
