package:
  name: titrato
  version: "0.0.5"

source:
  path: ../..

build:
  number: 0
  noarch: generic

requirements:
  build:
    - python=3.7
    - setuptools    

  run:
    - python=3.7
    - scipy=1.3
    - numpy=1.17
    - matplotlib=3.1
    - pandas=0.25
    - networkx=2.4
    - pydot=1.4
    - adjusttext=0.7.3
    - typing_extensions=3.7.4
    - tqdm=4.40
    - uncertainties=3.1
    - seaborn=0.9
    - statsmodels=0.10

test:
  requires:
    - pytest
  imports:
    - titrato

about:
  home: add_url_here
  license: MIT License
