package:
  name: titrato
  version: "0.0.4"

source:
  path: ../..

build:
  number: 0

requirements:
  build:
    - python=3.7
    - setuptools=42.0.2    

  run:
    - python=3.7
    - scipy=1.3.3
    - numpy=1.17.3
    - matplotlib=3.1.2
    - pandas=0.25.3
    - networkx=2.4
    - pydot=1.4.1
    - adjusttext=0.7.3.1
    - typing_extensions=3.7.4.1
    - tqdm=4.40.2
    - uncertainties=3.1.3
    - seaborn=0.9.0

test:
  requires:
    - pytest
  imports:
    - titrato

about:
  home: add_url_here
  license: MIT License
