package:
  name: titrato
  version: "0.0.1"

source:
  path: ../..

build:
  number: 0

requirements:
  build:
    - python
    - setuptools    

  run:
    - python
    - scipy
    - numpy
    - holoviews
    - matplotlib
    - pandas
    - networkx

test:
  requires:
    - pytest
  imports:
    - titrato

about:
  home: add_url_here
  license: MIT License
